// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcmzcadhryosfoyydvka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjbXpjYWRocnlvc2ZveXlkdmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTkzMTMsImV4cCI6MjA2Mjk5NTMxM30.7xQRdN_q3Q1N0NP0TImb_pbwtah4D8zIu6b6DhKyelU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);